LOOP LD INDICEIMPAR   
ML TWO
AD ONE
AD RESULTADOPARCIAL
MM RESULTADOPARCIAL
PTR MM ADDR
LD PTR
AD TWO         
MM PTR      
LD INDICEIMPAR
AD ONE
MM INDICEIMPAR
LD CONTADOR
AD ONE
MM CONTADOR         
SB LIMITE
JN LOOP
HM LOOP 

RESULTADOPARCIAL  K /0000  
LIMITE            K /003F   
ZERO              K /0000
ONE               K /0001
TWO               K /0002
INDICEIMPAR       K /0000   
CONTADOR          K /0000

@         /0100    
MSTART    K /0000   
ADDR      K /0000 